### ISSUE TITLE
Boot Button as an input device

### ISSUE THREAD

**Issue by kise1-off** [adafruit/Adafruit_Wippersnapper_Arduino#243]
Almost every ESP board has Boot Button.
This button is used during reloading to open the bootloader.
At other times, this button and GPIO pin can be used for input device in WipperSnapper.
It will be helpful to have an option to have a button that is already soldered onboard and does not require other connections.

**Comment by brentru** [comment]
We've added this to a number of boards within WipperSnapper Boards

For reference on how to add the boot-pushbutton, [add the following array to a board's definition](https://github.com/adafruit/Wippersnapper_Boards/blob/main/boards/qtpy-esp32/definition.json#L100) and check-out a PR.
