### ISSUE TITLE
Support for RP2040

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#246]
Support Raspberry Pi Pico Arduino core, for all RP2040 boards ([Earle Philhower's Arduino core](https://github.com/earlephilhower/arduino-pico))

**Comment by brentru** [comment]
Blocked via https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/280

**Comment by ladyada** [comment]
this was done!
