### ISSUE TITLE
Feather ESP32-S2 with BME-280 wrong temperature data

### ISSUE THREAD

**Issue by kise1-off** [adafruit/Adafruit_Wippersnapper_Arduino#255]
Feather ESP32-S2 with BME-280 incorrect temperature data. 
Because of the heating of the central controller, the sensor is always too high temperature.

**Comment by brentru** [comment]
@kise1-off  Is this in reference to the BME280 mounted on the ESP32-S2 Feather board?

**Comment by ladyada** [comment]
closing as no-response
