### ISSUE TITLE
Allow connecting to "open" (no password) network

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#276]
Similar to https://github.com/adafruit/Adafruit_IO_Arduino/issues/156. Once implemented here, issue can be fixed in AIO_Arduino as well.

**Comment by coredatascientist** [comment]
I'd be interested in this feature as when the password is left blank it currently results in a red neopixel.

**Comment by brentru** [comment]
We can do WiFi ENT via https://github.com/espressif/arduino-esp32/pull/6398
