### ISSUE TITLE
Feather esp32-v2 wippersnapper Fail to connect

### ISSUE THREAD

**Issue by Ottermoi** [adafruit/Adafruit_Wippersnapper_Arduino#347]
For some reason, i keep getting pop-up connectivity errors when I was trying to connect it to whippersnapper The cable I am using works as I have had code in Arduino uploaded to the module, but I made sure to check with other cables I restarted the board and the computer I have all the drivers installed it shows up in my Arduino but not in my device manager I wonder if that's the real issue.

**Comment by brentru** [comment]
@Ottermoi  Hi - What are the pop-up errors you're getting?

**Comment by brentru** [comment]
@Ottermoi  - is this issue still occurring?

**Comment by ladyada** [comment]
closing as no-response
