### ISSUE TITLE
Wippersnapper won't initialize VL53L0X sensor

### ISSUE THREAD

**Issue by ETJumper** [adafruit/Adafruit_Wippersnapper_Arduino#356]
When trying to add a VL53L0X I2C sensor, using the guide on Adafruit, I keep getting an error that I2C device failed initialization and the following message: 
"Your I2C Component at address 0x29 could not initialize: 
Error Message: Wippersnapper firmware is outdated and does not include the sensor type. Please update your Wippersnapper firmware."

Board is an Adafruit QT py ESP32 Pico.  Using Chrome browser Version 106.0.5249.119 (Official Build) (64-bit) on a Window Surface Laptop 3 running Windows 10 Pro.

I've tried removing and reinstalling the device (QT Py ESP32 Pico) with WipperSnapper. I2C Scan shows correct address. VL53L0X Sensor tested good with a regular QT Py (SAMD21).  Even tried rebooting the computer.  The QT Py will take a program (Blink) using the Arduino IDE.

**Comment by brentru** [comment]
I believe https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/291 was not completed by the original author and thus is not supported by WipperSnapper firmware despite being on the icon picker. We're working on a solution to hide these types of issues in the coming week.

You're welcome to either pick up this pull request (we have a guide on adding components here: https://learn.adafruit.com/how-to-add-a-new-component-to-adafruit-io-wippersnapper/adding-an-i2c-component-driver) or wait for us to add it to WipperSnapper.

**Comment by tyeth** [comment]
I'm going to push this forwards as my VL53L0X (and 1X) sensors have arrived

**Comment by brentru** [comment]
Addressing in https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/363

**Comment by tyeth** [comment]
@ETJumper give the latest version a try if you're still interested. It does return sensor data. 
Currently you'll need to select the checkbox to "Show Dev?" which will show components still under development:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/6692083/206434604-9fba8352-a482-4d30-9f08-9133aba02fd3.png">

## Notice the orange banner:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/6692083/206434826-59f27a44-6a9c-4cc9-b9ed-f882a8ab73f8.png">

I think this ticket can probably be closed and then bugs raised if necessary.

**Comment by brentru** [comment]
@tyeth  Do we still want this as an "in development" component, as it is now in Production? I can make it live if so.

**Comment by tyeth** [comment]
Make it so captain

**Comment by tyeth** [comment]
Sweet, it's there. No refreshing, but it was a new tab.
