### ISSUE TITLE
Issue attempting to add BME280 to adafruit.io

### ISSUE THREAD

**Issue by MoonGoddess** [adafruit/Adafruit_Wippersnapper_Arduino#362]
**Describe the bug**
I ordered a Adafruit ESP32-S2 TFT Feather board, a STEMMAQT cable and a BME280 board for a project.    Copied over the wippersnapper software, got my secrets file updated, got the board connected to the internet and can see it's online status on adafruit.io      Having now put the cable in and attached the BME280 I get a green light on the BME280, however the I2C scan on the website says nothing found,   Adding a LED component for the built in LED I am able to turn the LED on and off thru the website, so I know communication is happening.       Attempting to manually add the BME280 board  produces a "Error: Cannot read properties of undefined (reading 'toString')" upon hitting the create component button.

***Arduino board***
Adafruit ESP32-S2 TFT Feather

**To Reproduce**
1. Install Wippersnapper v1.0.0-beta.54 on ESP32
2. Connect BME280 board via StemmaQT cable
3. Click on +New Component 
4. Scroll down to BME280
5. See screenshot 1 
6.  Click "Create Component"
7. See error on screenshot 2.

**Expected behavior**
Expect to be able to select i2c port 77 to connect the BME280 to Adafruit.io

**Which components are connected to your device**
Only the BME280 which is not showing in Adafruit.io

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/4828745/200962383-6028237f-d26b-41ed-8ef5-b2ff65579f56.png)
![screenshot 2](https://user-images.githubusercontent.com/4828745/200962478-0a38af39-3f4a-4531-80f9-670c64ac580b.png)
![result of using i2c scan](https://user-images.githubusercontent.com/4828745/200962544-7e672ba0-ea33-457b-9325-29b156071c63.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19044.2251
 - Browser Google Chrome Version 107.0.5304.106 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - Browser Google Chrome

**Additional context**
Spoke with brentr about this issue on Discord, on 11/9/22

**Comment by MoonGoddess** [comment]
Just to confirm my wiring and equipment, I loaded CircuitPython to the board, and used the example code from this page, https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/python-circuitpython-test    was able to successfully read from the board.   Loading Wippersnapper back on the board results in the same errors above.

**Comment by brentru** [comment]
@lorennorman  Could you take a look at the `Error` message on the web form?

**Comment by lorennorman** [comment]
I will look at this in the morning, definitely looks like my bug somewhere in the Javascript. Thank you for the excellent bug report!

**Comment by brentru** [comment]
@MoonGoddess  This is similar to https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/345#issuecomment-1278147010 and I'm unable to reproduce with the same hardware setup:
![image](https://user-images.githubusercontent.com/322428/201395529-1f7a135b-74e5-4837-9cab-61555f84c2a0.png)


Could you try **deleting** the ESP32-S2 TFT Feather from your Adafruit IO devices page. Then, refresh your tab and reconnect your board. Please let me know if it's working for you. I tested it as well with a similar setup:

**Comment by MoonGoddess** [comment]
I am now working,  if you look closely at the screenshots above you may notice, I put the board into Adafruit.io as a ESP32-S2 **without**   TFT.   I'm a dummy.

**Comment by brentru** [comment]
ok! Thanks for updating us on what worked.
