### ISSUE TITLE
Allow multiple network SSIDs to be defined within secrets.json file

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#376]
Allow for multiple SSIDs to be defined within secrets.json, by priority
```
"network_type_wifi":[
          {
		"network_ssid":"my_house",
		"network_password":"password"
	},
        {
		"network_ssid":"the_garden",
		"network_password":"password"
	}
]
```

via @tyeth  on https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/issues/328#issuecomment-1253956614
> I think long term I'd love the support of single object and/or array for networks, and to potentially add a key for priority, or potentially just use RSSI based priority upon start/disconnect. i.e. currently it's:

**Comment by isomorphic85** [comment]
YES, this would be amazing

**Comment by brentru** [comment]
This should be simple with the new WiFiMulti library inside BSP 3.x

https://docs.espressif.com/projects/arduino-esp32/en/latest/api/wifi.html#wifimulti

**Comment by brentru** [comment]
@tyeth  Want to tackle this one next week?

**Comment by tyeth** [comment]
This has been added under the new additional key of `alternative_networks`.

Please see this playground note for details:
https://adafruit-playground.com/u/tyeth/pages/using-multiple-wifi-network-credentials-in-adafruit-io-wippersnapper-firmware
