### ISSUE TITLE
First Installation on my ESP32

### ISSUE THREAD

**Issue by MorkBorlog** [adafruit/Adafruit_Wippersnapper_Arduino#420]
**Hi! I'm trying to install your service on my ESP32, but I get this error message. What can I do there?**

```
In file included from c:\Users\patri\OneDrive\Dokumente\Arduino\libraries\Adafruit_WipperSnapper\src/Wippersnapper.h:47,
                 from c:\Users\patri\OneDrive\Dokumente\Arduino\libraries\Adafruit_WipperSnapper\src/network_interfaces/Wippersnapper_ESP8266.h:24,
                 from c:\Users\patri\OneDrive\Dokumente\Arduino\libraries\Adafruit_WipperSnapper\src/Wippersnapper_Networking.h:25,
                 from C:\Users\patri\AppData\Local\Temp\.arduinoIDE-unsaved2023211-1988-7eegw0.nrjml\Wippersnapper_NoFS\Wippersnapper_NoFS.ino:19:
c:\Users\patri\OneDrive\Dokumente\Arduino\libraries\Adafruit_WipperSnapper\src/components/ds18x20/ws_ds18x20.h:22:10: fatal error: DallasTemperature.h: No such file or directory
   22 | #include <DallasTemperature.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
```

EDIT: I have ESP32-CAM. This no works on your Cloud? :(

**Comment by brentru** [comment]
@MorkBorlog Hi, the ESP32-CAM is not a supported board. However, the ESP32 architecture is supported which means you can add it to WipperSnapper!

We have a guide for adding a supported board to Adafruit IO WipperSnapper here: https://learn.adafruit.com/how-to-add-a-new-board-to-wippersnapper?view=all

Let me know by creating a **new** issue if you encounter any difficulties with following that guide.
