### ISSUE TITLE
PMSA003I Reads 0ppm

### ISSUE THREAD

**Issue by videopixil** [adafruit/Adafruit_Wippersnapper_Arduino#421]
**Describe the bug**
PMSA003I Reads 0ppm. CircuitPython example code reads values higher than 0. Particles .3 and .5um frequently show higher values. Particles 2.5 through 10um frequently show 0 values more often. 

***Arduino board***
Feather ESP32-S2 and Feather TFT Reverse S3

**To Reproduce**
add component in wippersnapper

**Expected behavior**
WipperSnapper Values should show values shown in CircuitPython code

**Which components are connected to your device**
PMSA003I

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: safari
 - Version 16.3

**Smartphone (please complete the following information):**
 - Device: iPhone 13pro
 - 16.3.1
 - Browser safari
 - Version 16.3.1

**Additional context**

**Comment by brentru** [comment]
Soaking this overnight

**Comment by brentru** [comment]
Unable to reproduce on latest build of Wippersnapper, please update your board's firmware and try again.
