### ISSUE TITLE
I2C fails to find device

### ISSUE THREAD

**Issue by HunterFray** [adafruit/Adafruit_Wippersnapper_Arduino#422]
I2c scan does not find the STEMMA soil sensor I have attached to the pico w I am using, I have confirmed that pins for SCL and SDA are connected to the correct pins and that the pico is able to communicate with the sensor if circuitpython is installed instead of wippersnapper.

No matching, unused addresses found! is the error shown when trying to add the component.
Running an i2c scan from the dashboard for the pico also finds no usable addresses.

<img width="401" alt="i2c" src="https://user-images.githubusercontent.com/114106016/228211047-a50f0aa7-590e-41bc-b81b-eef686695959.PNG">

**Comment by brentru** [comment]
@HunterFray  Do you know which version of WipperSnapper you're running on the PicoW?

**Comment by brentru** [comment]
@HunterFray  

I'm unable to replace this on WipperSnapper Beta v61 connected to a STEMMA soil sensor. Please verify your wiring and connections and try again.

If that does not work - please attach a photo of your wiring (top-down is preferred) to this issue.


Create Soil Sensor Form:
![image](https://user-images.githubusercontent.com/322428/231004402-3e3571e4-0e6a-49e3-887c-6797b76edd7f.png)

**Comment by brentru** [comment]
Due to lack of response and inability for me to reproduce it, I am closing this issue.

Please feel free to re-open it and tag me if you are still having this issue.
