### ISSUE TITLE
ESP8266 Compilation error

### ISSUE THREAD

**Issue by rocketrob** [adafruit/Adafruit_Wippersnapper_Arduino#434]
Compilation error: no matching function for call to 'Wippersnapper_ESP8266::Wippersnapper_ESP8266(const char [10], const char [33], const char [11], const char [11])'

***Arduino board***
Amica NodeMCU Generic ESP8266

**To Reproduce**

**Expected behavior**
Compile and upload WipperSnapper to device for adding to My Device page on WipperSnapper

**Which components are connected to your device**
Which components are set up on the WipperSnapper device page? n/a

**Screenshots** 
If applicable, add screenshots to help explain your problem. n/a

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  - Windows 11
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):** n/a

**Additional context**

**Comment by brentru** [comment]
@rocketrob  I am going to reproduce this but I need more information. On this menu, which board did you select:

![image](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/assets/322428/e9caaaa8-114b-4cc0-ad01-ee1931f8b056)

**Comment by rocketrob** [comment]
I tried both the generic ESP8266 and the adafruit feather hazzah ESP8266

How that helps

Rob

**Comment by brentru** [comment]
@rocketrob You're attempting to load WipperSnapper on an Amica NodeMCU Generic ESP8266, right? What board do you typically select for this? 

btw - this board is unsupported, I assume you are adding it to WipperSnapper and following the guide: https://learn.adafruit.com/how-to-add-a-new-board-to-wippersnapper

**Comment by brentru** [comment]
@rocketrob  I do not get a compilation error when I compile for the Huzzah ESP8266. 

When I attempt to compile for the "Generic ESP8266" board, I get a compilation error. This error is expected for not-yet-supported boards such as the Generic ESP8266 platform. 

```
/Users/brentrubell/Documents/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/Wippersnapper.cpp: In member function 'bool Wippersnapper::generateDeviceUID()':
/Users/brentrubell/Documents/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/Wippersnapper.cpp:1684:17: error: 'BOARD_ID' was not declared in this scope
 1684 |   WS._boardId = BOARD_ID;
      |                 ^~~~~~~~
In file included from /Users/brentrubell/Documents/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/Wippersnapper.cpp:34:
/Users/brentrubell/Documents/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/Wippersnapper.cpp: In function 'void printDeviceInfo()':
/Users/brentrubell/Documents/Arduino/libraries/Adafruit_Wippersnapper_Arduino/src/Wippersnapper.cpp:2490:20: error: 'BOARD_ID' was not declared in this scope
 2490 |   WS_DEBUG_PRINTLN(BOARD_ID);
      |                    ^~~~~~~~
```

To resolve it, closely follow the steps in the Adafruit Learning System Guide for "Modifying Firmware | How to Add a Board to WipperSnapper": https://learn.adafruit.com/how-to-add-a-new-board-to-wippersnapper/modifying-firmware


If you need assistance porting a board to WipperSnapper, please open a new issue in this repository.
