### ISSUE TITLE
Feature Req: Would be nice if Sensor always sent a reading when first added

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_Wippersnapper_Arduino#463]
Currently if a sensor is added it defaults each metric to 15mins, and doesn't send a value to adafruit IO until that polling period is expired.

It would be nice if new sensor metrics/feeds always sent data upon initialisation (although this also has rate consequences)

**Comment by brentru** [comment]
@tyeth  Do you want to tackle this one?

**Comment by tyeth** [comment]
Just occurred to me while thinking about this one, that it's possible some users are rate limiting themselves using the period as a starting offset. This is unlikely, but possible.
