### ISSUE TITLE
"Dimmable LED" Component on HUZZAH ESP8266 is inverted

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#495]
**Describe the bug**
The dimmable LED component's functionality is inverted when used with the Feather Huzzah ESP8266:

![IO_-_Device__Feather_Huzzah_ESP8266_🔊](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/assets/322428/ee006f68-29c0-4fb8-bd29-0282c7ca0a74)

This may be caused due to the fact that the Adafruit Feather Huzzah ESP8266 has inverted wiring on the RED LED.

***Arduino board***
INSERT ARDUINO BOARD NAME/TYPE HERE

**To Reproduce**
1. Create a new Dimmable LED Component
2. Drag the slider to 100%
3. Drag the slider back to 0%

**Which components are connected to your device**
Dimmable LED (D0)

**Comment by brentru** [comment]
@tyeth  Wanna take a look at this issue?

**Comment by tyeth** [comment]
This sounds like something for the analog output basics guide, so we show a normal one and mention / explain how that would play out if you had it wired oppositely (i.e. the LED would be on with the Low part of the duty cycle), like you find on some boards.
