### ISSUE TITLE
v74 / staging - Infinite "Polling for message containing hardware configuration..."

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_Wippersnapper_Arduino#513]
Appears to happen after successful hardware configuration.
[serial_output_v74_esp32v2.txt](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/files/13477695/serial_output_v74_esp32v2.txt)

Same after a reboot.

![image](https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/assets/6692083/577fad94-d6f6-45ab-9a21-a039324f395e)

I'll now delete the device from staging and reset it

**Comment by brentru** [comment]
Confirming that I can replicate this on alpha 74

**Comment by brentru** [comment]
@tyeth  Loren fixed a check for alpha vs beta on staging, this works perfectly for me on FeatherS3 NO PSRAM on alpha74/staging with a magic config.
