### ISSUE TITLE
Preprocessor script for printing the library versions to boot_out.txt

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Wippersnapper_Arduino#598]
Create a preprocessor script to enumerate the arduino libaries and their versions into a string. The string should be placed into a header file. The header file is then included in the firmware, compiled in, and the string should be printed to the `boot_out.txt` file.

1. Create the preprocessor script
1a. Enumerate the libraries, obtain their names and versions, store in a string, generate header file containing this string
3. Include the header file in the firmware
4. Write the string from the header file to the boot_out.txt
5. Modify the existing build script to accommodate the steps above

This was requested by @ladyada  during the Wednesday CE meeting

**Comment by tyeth** [comment]
Just spotted this issue, can't believe I missed it 🤦 

Looks like I can get what we need from the arduino-cli using --only-compilation-database as this outputs exactly what we need. Not sure that is doesn't just do a build anyway. 
 Currently testing with 
```
arduino-cli.exe --additional-urls="https://adafruit.github.io/arduino-board-index/package_adafruit_index.json,http://arduino.esp8266.com/stable/package_esp8266com_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json,https://sandeepmistry.github.io/arduino-nRF5/package_nRF5_boards_index.json,https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json" compile -b esp32:esp32:adafruit_metro_esp32s2 ..\examples\Wippersnapper_demo --only-compilation-database
```
