### ISSUE TITLE
Migrate Actions to upload-artifact v4 - Requires separately named artifacts per build task, then a merge step

### ISSUE THREAD

**Issue by tyeth** [adafruit/Adafruit_Wippersnapper_Arduino#611]
The action version is deprecated (v1-v3), and v4 has breaking changes.
See https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
And the step we'll need here:
https://github.com/actions/upload-artifact/blob/main/merge/README.md#combining-all-artifacts-in-a-workflow-run

**Comment by tyeth** [comment]
I was upgrading some action versions while working on #607 to see if it resolved some issues I was having, but this felt like a larger lift / separate piece of work.

**Comment by brentru** [comment]
@tyeth  I've updated this to V3 instead of V4, we should look at upgrading to V4 as V3 will expired in November 2024.
