### ISSUE TITLE
Data recorded in stuttering manner with SCD-30 and many boards (QT PY S2, QT PY S3, etc) - in Release 0.88

### ISSUE THREAD

**Issue by kcowin** [adafruit/Adafruit_Wippersnapper_Arduino#627]
**Describe the bug**

SCD-30 sensor has four feeds that can be accessed. When sending the feeds
to wippersnapper every 30 seconds, they show up randomly.

![Screenshot Data Problem 2024-09-06 165114](https://github.com/user-attachments/assets/92709096-47a4-4693-87fd-07ab85777bcd)

**To Reproduce**

Attach an SCD-30 to a QT PY Board and see if you can get better results.

**Expected behavior**
You will likely see missing values, if any at all.

**Which components are connected to your device**
Which components are set up on the WipperSnapper device page?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Problem appears regardless of browser or browsing platform. There are no data errors
on the wippersnapper subscription page.

**Comment by tyeth** [comment]
Provisional fix in PR. @kcowin if you wish to try the build assets they are attached 
[issue632-qtpy-assets.zip](https://github.com/user-attachments/files/17063533/issue632-qtpy-assets.zip)

**Comment by tyeth** [comment]
I've been running it for a couple of days, at 30second intervals so about 3500(3467) readings. 

The temp/humidity get read in one command, and then the CO2 afterwards (so more chance of a failure).

Approximately 35 CO2 readings (1%) were more that 30seconds apart, the majority at 60s apart (so a reading was skipped), a sprinkle at 90s (two readings skipped), and a few further apart (presumably connectivity issues or account throttle).

Temperature readings had 10 entries out of 3500 that didn't fall in the 30second poll period.

![image](https://github.com/user-attachments/assets/ceda8821-9beb-49d6-9c94-07ce2b80f704)

**Comment by kcowin** [comment]
Yes- I noticed it was not perfect, but a substantial improvement, and now the data is usable. KenSent from my iPhoneOn Sep 23, 2024, at 7:57 AM, Tyeth Gundry ***@***.***> wrote:﻿
I've been running it for a couple of days, at 30second intervals so about 3500(3467) readings.
The temp/humidity get read in one command, and then the CO2 afterwards (so more chance of a failure).
Approximately 35 CO2 readings (1%) were more that 30seconds apart, the majority at 60s apart (so a reading was skipped), a sprinkle at 90s (two readings skipped), and a few further apart (presumably connectivity issues or account throttle).
Temperature readings had 10 entries out of 3500 that didn't fall in the 30second poll period.
image.png (view on web)
